# Vigilant-Guard Configuration
owner: iamprmgvyt
repo: Vigilant-Guard

# List of sites to monitor
sites:
  - name: Google
    url: https://www.google.com
  - name: My Site
    url: https://www.prmgvyt.io.vn/ # Thay link web của bạn vào đây

# Status Page Setup
status-page:
  basename: /Vigilant-Guard/
  title: Vigilant-Guard Status
  introMessage: This is a 24/7 monitoring service.
  navbar:
    - title: Status
      href: /Vigilant-Guard/
    - title: GitHub
      href: https://github.com/iamprmgvyt/Vigilant-Guard

assignees: [iamprmgvyt]
